# Generated by Django 4.2.2 on 2023-11-10 08:13

import SharedRides.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='example@example.com', max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='Fname', max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(default='Lname', max_length=128, verbose_name='Last Name')),
                ('contact_number', models.BigIntegerField(null=True, validators=[SharedRides.models.ContactNumberValidator], verbose_name='Contact Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cluster', models.TextField(default='[]')),
                ('travel_distance', models.FloatField(default=0.0)),
                ('start_place', models.TextField(blank=True, verbose_name='Starting Place')),
                ('end_place', models.TextField(blank=True, verbose_name='Ending Place')),
                ('participants', models.ManyToManyField(blank=True, related_name='participant_trips', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('start_place', models.TextField(blank=True, verbose_name='Pick-up Location')),
                ('end_place', models.TextField(blank=True, verbose_name='Drop-off Location')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined')], max_length=20)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedRides.trip')),
            ],
        ),
    ]
