# Generated by Django 4.2.2 on 2023-11-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedRides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.CharField(max_length=100),
        ),
    ]
