# Generated by Django 4.2.2 on 2023-11-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedRides', '0003_alter_trip_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.CharField(max_length=100),
        ),
    ]
