# Generated by Django 4.2.2 on 2023-11-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharedRides', '0004_remove_trip_description_alter_trip_available_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passengers',
        ),
    ]
